<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit53f212c7733183e1deebde32a5ce5d75
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('FavrDirectory\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \FavrDirectory\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit53f212c7733183e1deebde32a5ce5d75', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \FavrDirectory\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit53f212c7733183e1deebde32a5ce5d75', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\FavrDirectory\Vendor\Composer\Autoload\ComposerStaticInit53f212c7733183e1deebde32a5ce5d75::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
