<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'FavrDirectory\\Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'FavrDirectory\\Vendor\\FavrCore\\Admin\\FieldRenderer' => $vendorDir . '/favr/core/src/Admin/FieldRenderer.php',
    'FavrDirectory\\Vendor\\FavrCore\\Approvals\\Inbox' => $vendorDir . '/favr/core/src/Approvals/Inbox.php',
    'FavrDirectory\\Vendor\\FavrCore\\Fields\\FieldSet' => $vendorDir . '/favr/core/src/Fields/FieldSet.php',
    'FavrDirectory\\Vendor\\FavrCore\\Fields\\Sanitizer' => $vendorDir . '/favr/core/src/Fields/Sanitizer.php',
    'FavrDirectory\\Vendor\\FavrCore\\Integrations\\Elementor\\Widget' => $vendorDir . '/favr/core/src/Integrations/Elementor/Widget.php',
    'FavrDirectory\\Vendor\\FavrCore\\Moderation\\PendingChanges' => $vendorDir . '/favr/core/src/Moderation/PendingChanges.php',
    'FavrDirectory\\Vendor\\FavrCore\\Moderation\\Uploads' => $vendorDir . '/favr/core/src/Moderation/Uploads.php',
    'FavrDirectory\\Vendor\\FavrCore\\Support\\AssetVersion' => $vendorDir . '/favr/core/src/Support/AssetVersion.php',
    'FavrDirectory\\Vendor\\FavrCore\\Support\\CsvFormat' => $vendorDir . '/favr/core/src/Support/CsvFormat.php',
    'FavrDirectory\\Vendor\\FavrCore\\Support\\Hours' => $vendorDir . '/favr/core/src/Support/Hours.php',
    'FavrDirectory\\Vendor\\FavrCore\\Support\\RateLimit' => $vendorDir . '/favr/core/src/Support/RateLimit.php',
    'FavrDirectory\\Vendor\\FavrCore\\Support\\Template' => $vendorDir . '/favr/core/src/Support/Template.php',
);
