<?php

// autoload_static.php @generated by Composer

namespace FavrDirectory\Vendor\Composer\Autoload;

class ComposerStaticInit53f212c7733183e1deebde32a5ce5d75
{
    public static $prefixLengthsPsr4 = array (
        'F' =>
        array (
            'FavrDirectory\\Vendor\\FavrCore\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FavrDirectory\\Vendor\\FavrCore\\' =>
        array (
            0 => __DIR__ . '/..' . '/favr/core/src',
        ),
    );

    public static $classMap = array (
        'FavrDirectory\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FavrDirectory\\Vendor\\FavrCore\\Admin\\FieldRenderer' => __DIR__ . '/..' . '/favr/core/src/Admin/FieldRenderer.php',
        'FavrDirectory\\Vendor\\FavrCore\\Approvals\\Inbox' => __DIR__ . '/..' . '/favr/core/src/Approvals/Inbox.php',
        'FavrDirectory\\Vendor\\FavrCore\\Fields\\FieldSet' => __DIR__ . '/..' . '/favr/core/src/Fields/FieldSet.php',
        'FavrDirectory\\Vendor\\FavrCore\\Fields\\Sanitizer' => __DIR__ . '/..' . '/favr/core/src/Fields/Sanitizer.php',
        'FavrDirectory\\Vendor\\FavrCore\\Moderation\\PendingChanges' => __DIR__ . '/..' . '/favr/core/src/Moderation/PendingChanges.php',
        'FavrDirectory\\Vendor\\FavrCore\\Moderation\\Uploads' => __DIR__ . '/..' . '/favr/core/src/Moderation/Uploads.php',
        'FavrDirectory\\Vendor\\FavrCore\\Support\\AssetVersion' => __DIR__ . '/..' . '/favr/core/src/Support/AssetVersion.php',
        'FavrDirectory\\Vendor\\FavrCore\\Support\\CsvFormat' => __DIR__ . '/..' . '/favr/core/src/Support/CsvFormat.php',
        'FavrDirectory\\Vendor\\FavrCore\\Support\\Hours' => __DIR__ . '/..' . '/favr/core/src/Support/Hours.php',
        'FavrDirectory\\Vendor\\FavrCore\\Support\\Template' => __DIR__ . '/..' . '/favr/core/src/Support/Template.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit53f212c7733183e1deebde32a5ce5d75::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit53f212c7733183e1deebde32a5ce5d75::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit53f212c7733183e1deebde32a5ce5d75::$classMap;

        }, null, ClassLoader::class);
    }
}
